---
name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - services/**
      - .github/workflows/test.yaml

  pull_request: 
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml

  test:
    runs-on: ubuntu-24.04
    needs: filter
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        if: startsWith(matrix.service, 'services/node/') || startsWith(matrix.service, 'services/react/') 
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: "${{ matrix.service }}/package.json"
          cache: npm
          cache-dependency-path: "${{ matrix.service }}/package-lock.json"

      - name: Setup golang
        if: startsWith(matrix.service, 'services/go/')
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "${{ matrix.service }}/go.mod"
          cache-dependency-path: "${{ matrix.service }}/go.sum"

      - name: Setup Poetry
        if: startsWith(matrix.service, 'services/python/')
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1

      - name: Setup Python
        if: startsWith(matrix.service, 'services/python/')
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: "${{ matrix.service }}/pyproject.toml"
          cache: poetry
          cache-dependency-path: "${{ matrix.service }}/poetry.lock"

      - name: Install task
        uses: supplypike/setup-bin@1fafb085795af4a3f183502f3a9dffa8f7b83217 # v5.0.0
        with:
          uri: "https://github.com/go-task/task/releases/download/v3.48.0/task_linux_amd64.tar.gz"
          name: task
          version: v3.48.0

      - name: Install dependancies
        working-directory: ${{ matrix.service }}
        run: task install-ci

      - name: Run Tests
        working-directory: ${{ matrix.service }}
        run: task test
